name: CI & Deploy
on:
	push:
		branches: [ main ]
jobs:
	build-test-deploy:
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v4
			- uses: actions/setup-node@v4
			  with:
			    node-version: 18
			- name: Install root deps
			  run: npm ci || npm install
			- name: Install functions deps
			  working-directory: functions
			  run: npm ci || npm install
			- name: Build functions
			  working-directory: functions
			  run: npm run build
			- name: Run tests
			  run: npm test --if-present
			- name: Firebase Deploy
			  uses: w9jds/firebase-action@v13.29.2
			  with:
			    args: deploy --only hosting,functions
			  env:
			    FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}






