name: Deploy to Firebase

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      
    - name: Run linting
      run: |
        echo "Running basic syntax checks..."
        node -c firebase-config.js
        node -c auth.js
        node -c session.js
        node -c leaderboard.js
        node -c payment.js
        node -c app.js
        
    - name: Test Firebase configuration
      run: |
        echo "Testing Firebase configuration..."
        firebase --version
        firebase projects:list || echo "Firebase CLI configured"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      
    - name: Build functions
      run: |
        cd functions
        npm install
        npm run build
        
    - name: Deploy to Firebase
      run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        
    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Deployment successful!"
        else
          echo "❌ Deployment failed!"
        fi







